require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ItemSchemasController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ItemSchema. As you add validations to ItemSchema, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItemSchemasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all item_schemas as @item_schemas" do
      item_schema = ItemSchema.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:item_schemas)).to eq([item_schema])
    end
  end

  describe "GET #show" do
    it "assigns the requested item_schema as @item_schema" do
      item_schema = ItemSchema.create! valid_attributes
      get :show, {:id => item_schema.to_param}, valid_session
      expect(assigns(:item_schema)).to eq(item_schema)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ItemSchema" do
        expect {
          post :create, {:item_schema => valid_attributes}, valid_session
        }.to change(ItemSchema, :count).by(1)
      end

      it "assigns a newly created item_schema as @item_schema" do
        post :create, {:item_schema => valid_attributes}, valid_session
        expect(assigns(:item_schema)).to be_a(ItemSchema)
        expect(assigns(:item_schema)).to be_persisted
      end

      it "redirects to the created item_schema" do
        post :create, {:item_schema => valid_attributes}, valid_session
        expect(response).to redirect_to(ItemSchema.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved item_schema as @item_schema" do
        post :create, {:item_schema => invalid_attributes}, valid_session
        expect(assigns(:item_schema)).to be_a_new(ItemSchema)
      end

    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested item_schema" do
        item_schema = ItemSchema.create! valid_attributes
        put :update, {:id => item_schema.to_param, :item_schema => new_attributes}, valid_session
        item_schema.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested item_schema as @item_schema" do
        item_schema = ItemSchema.create! valid_attributes
        put :update, {:id => item_schema.to_param, :item_schema => valid_attributes}, valid_session
        expect(assigns(:item_schema)).to eq(item_schema)
      end

      it "redirects to the item_schema" do
        item_schema = ItemSchema.create! valid_attributes
        put :update, {:id => item_schema.to_param, :item_schema => valid_attributes}, valid_session
        expect(response).to redirect_to(item_schema)
      end
    end

    context "with invalid params" do
      it "assigns the item_schema as @item_schema" do
        item_schema = ItemSchema.create! valid_attributes
        put :update, {:id => item_schema.to_param, :item_schema => invalid_attributes}, valid_session
        expect(assigns(:item_schema)).to eq(item_schema)
      end

    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested item_schema" do
      item_schema = ItemSchema.create! valid_attributes
      expect {
        delete :destroy, {:id => item_schema.to_param}, valid_session
      }.to change(ItemSchema, :count).by(-1)
    end

    it "redirects to the item_schemas list" do
      item_schema = ItemSchema.create! valid_attributes
      delete :destroy, {:id => item_schema.to_param}, valid_session
      expect(response).to redirect_to(item_schemas_url)
    end
  end

end
